### ISSUE TITLE
Feature Request: Option whether to allow items with NBT to be inserted.

### ISSUE THREAD

**Issue by MindCaged** [pkmnfrk/equivalentintegrations#13]
Okay, I'm loving this mod so far. Hooked it up to my AE system and it makes crafting stuff really easy. I am however having a problem. If I hook it up with a storage bus and set a higher priority so that it tries to put stuff in the transmutation chamber first it burns anything with EMC that I put into the system, even if it has NBT values like enchantments or other important information. For example pickaxes with enchantments, Akashic Tomes with manuals stored in them, Thaumcraft vis crystals, etc. And trying to blacklist all those potential items in ProjectE from having EMC is well, impractical.

What I think would be nice is if the Transmutation Chamber did not allow these items to be auto-inserted by default, and have a checkbox or something in the interface if you /really/ want to allow items like that to be inserted. So you could have one Chamber hooked to the AE system to autocraft stuff, and say one with the option enabled hooked up to a mob farm and have it eat any enchanted item drops you don't really care about. Though it'd also be useful to sort out enchanted mob drops from non-enchanted, say if you wanted enchanted stuff to feed an enchantment generator from Extra Utils.

**Comment by pkmnfrk** [comment]
Hmm... I see what you're saying.

My initial reaction is "Well, ProjectE doesn't distinguish, so I won't either", but I guess the use case is significantly different from ProjectE vanilla, so I guess it can be done.

**Comment by pkmnfrk** [comment]
This is done in v0.1.7
