### ISSUE TITLE
Crash after updating from EI v0.1.9 to v0.1.10

### ISSUE THREAD

**Issue by ate0ate** [pkmnfrk/equivalentintegrations#23]
After attempting to update I now get this crash at startup...
https://pastebin.com/tqsqMsxP

I am running a large 1.12.2 personal pack using forge 14.23.5.2811 and Project E v1.4.0. I have been using Equivalent Integrations 0.1.9 without issue for quite some time now and only crash after attempting to update. I did try to delete the config and allow it to regen but that did not have any effect.

**Comment by pkmnfrk** [comment]
That's odd. The only difference between 0.1.9 and 0.1.10 is that one line of code unrelated to the Transmutation Chamber changed. Let me take a look.

As an aside, in the future please include the rest of the crash log, not just the stack trace. I doubt it's relevant this time, but it has other useful info.

**Comment by ate0ate** [comment]
All apologies. I always worry about providing unnecessary info, but I suppose it is wiser to err on the side of caution. Here is a link to the relevant crash report and debug log...
http://www.mediafire.com/folder/g55olm8xgx494/Log_Uploads

**Comment by pkmnfrk** [comment]
No worries. Like I suspected, it wasn't relevant. It has just been so long since the last release that I messed up and made a deobfuscated build, which will not work in normal environments. My apologies, but expect an update in the very near future

**Comment by pkmnfrk** [comment]
You can get the fixed build here:

https://github.com/pkmnfrk/equivalentintegrations/releases/tag/v0.1.10a

**Comment by ate0ate** [comment]
Wow, that was very fast. Thanks!
