### ISSUE TITLE
New items cannot being taught in multiplayer issue

### ISSUE THREAD

**Issue by Goldenlion5648** [pkmnfrk/equivalentintegrations#24]
The pack is Project Ozone 3. New items can not be taught to the AE system by players who dont have their talisman connected to the system. So in my case, a transmutation chamber is connected to the system with a storage bus that has highest priority, that has my talisman in it. When other players try to put items into the system to teach the item, it is not taught, seems to be eaten (item put in is not visible in the system at all). Might update this later, but this was only tested when I was not logged on, not sure if that was a factor.

**Comment by pkmnfrk** [comment]
Hi, thanks for the report!

Unfortunately, as noted on the wiki page for [the Alchemical Algorithms](https://github.com/pkmnfrk/equivalentintegrations/wiki/Alchemical-Algorithms), learning new items is not possible when the linked player is offline. This is a limitation in ProjectE, and trying to work around it would be very cumbersome.

Sorry about that!

**Comment by pkmnfrk** [comment]
I did just update the Transmutation Chamber page to note this as well, to increase the visibility of this limitation.

**Comment by Goldenlion5648** [comment]
Would it be possible to make it so that if the talisman owner is not online then the items that other players put in are put on the disks instead of being deleted?

**Comment by pkmnfrk** [comment]
Eh? That's not supposed to happen. I will investigate.

**Comment by pkmnfrk** [comment]
Ok, so, in fairness, something must have changed in ProjectE. For some reason, in 1.4, offline players claim to know all items.

Anyway, in the next release, EI will be more aggressive about ensuring that the player can learn the item before consuming them.

That said, you should still have had the EMC from the consumed items, so you shouldn't have really lost anything.

**Comment by pkmnfrk** [comment]
You can test the fix in this beta release:

https://github.com/pkmnfrk/equivalentintegrations/releases/tag/v0.2.0
