### ISSUE TITLE
Exponential cpu usage

### ISSUE THREAD

**Issue by Elmegaard** [pkmnfrk/equivalentintegrations#33]
I am not sure if this is actually because of your mod, but I am 90% sure it is, as I did not see this issue before adding it. But I did update ProjectE and ProjectEX as part of adding your mod.

The game is running fine for about 10 minutes until it slows down more and more. It takes me like 3x as much time to eat chicken for example and fighting is pretty hard since everything is kind of delayed.

Leaving the game and rejoining will crash the game with the following error message: https://pastebin.com/MhfrmGC5

After reopening again it works fine for 10 more minutes. I have a champer hooked up to an ME system, with a charm and 4 of the efficiency thingies, that is all I use from the mod.

Btw, great mod I love it.

**Comment by pkmnfrk** [comment]
> Btw, great mod I love it.

Thanks!

> All the bad stuff

Hm... while I can hope that it's not my mod, I am usually wrong. In this case, only one thing really changed from the last version, and I can conceive of it causing problems. Please allow me to investigate...

**Comment by pkmnfrk** [comment]
Sorry, a few questions:

1. Are you running Single Player or Multi Player?
2. I assume you have lots of EMC, and lots of items in your Tranmutation Table. Is that accurate?
3. What mod pack are you playing (if it's a premade one)?

**Comment by Elmegaard** [comment]
1. Singleplayer
2. Very accurate
3. Sky Odyssey

Well, I did a restart and it has been good for nearly an hour. Not sure if it is fixed, but it seems a bit random. I didn't change anything.

**Comment by pkmnfrk** [comment]
No worries. In spite of the randomness, I would like if you could test a new version of the mod that, if it is what I think it is, should fix the issue. If it does still happen, then either it will give me more debugging info, or we can actually rule it out.

[EquivalentIntegrations-0.4.5.jar.zip](https://github.com/pkmnfrk/equivalentintegrations/files/3124450/EquivalentIntegrations-0.4.5.jar.zip)

If it happens again, then please grab latest.log and upload it to gist or pastebin so I can have a look. If not, then... well, eventually I'll go "must've fixed it" and make a new full release :)

**Comment by Elmegaard** [comment]
I will try it, but as I said, haven't seen it for an hour or so now. If it happens again I'll get back to you.

**Comment by pkmnfrk** [comment]
Let's make this easy: keep playing for now, if it happens again (or you stop for another reason), swap in the new version, see what happens. No rush on this on my end

**Comment by Elmegaard** [comment]
I swapped in the new version now, we'll see if it happens again. If not, I guess it was fixed ;)

**Comment by pkmnfrk** [comment]
👍

**Comment by pkmnfrk** [comment]
In case this crops up again, I've made a new release (v0.4.5) that contains this fix (plus the other bug), so you should be free to upgrade whenever you choose.

**Comment by Elmegaard** [comment]
I've played all day yesterday and I haven't been able to reproduce it. I am closing it for now. Thanks for the fixes.
