### ISSUE TITLE
Using AE2 with Transmutation Chamber is very laggy

### ISSUE THREAD

**Issue by Elmegaard** [pkmnfrk/equivalentintegrations#35]
After updating to 0.1.45, adding an item to the Transmutation Chamber using an AE2 terminal causes a lag spike. On top of that it no longer want to EMC damaged equipment even with the setting set correctly in the chamber. I have tested with a damaged bow and a damaged shovel, neither works.

I tried turning off the chamber (setting low priority) and the lag stopped but obviously it did not use the chamber in that case.

**Comment by pkmnfrk** [comment]
Can you post your latest.log?

**Comment by Elmegaard** [comment]
[latest.log](https://github.com/pkmnfrk/equivalentintegrations/files/3127575/latest.log)

**Comment by Elmegaard** [comment]
After playing for a bit I realise that every time my mob farm adds a bow to the system a 1-2 second lag where everything stops happens. I am playing in multiplayer now btw, not sure if it changes anything.

I played 0.1.44 on multiplayer yesterday without this issue.

**Comment by Elmegaard** [comment]
If you want me to show you how I reproduce it you can join my server.

**Comment by pkmnfrk** [comment]
I'll consider it.

But for now, can you try this build? It definitely fixes the "unable to learn" bug, and I think it will also fix the performance issue.

[EquivalentIntegrations-0.4.6.jar.zip](https://github.com/pkmnfrk/equivalentintegrations/files/3127741/EquivalentIntegrations-0.4.6.jar.zip)

**Comment by Elmegaard** [comment]
Way to go, it works.

**Comment by b-chu** [comment]
Still lagging in 0.4.6 #47
