### ISSUE TITLE
Support for Minecraft 1.13

### ISSUE THREAD

**Issue by pkmnfrk** [pkmnfrk/equivalentintegrations#4]
This can't happen until ProjectE does, but may as well track this now.

**Comment by auddie2015** [comment]
Any plans for 1.10.2? (not a bug of course, just a question.)

**Comment by pkmnfrk** [comment]
Nope!

**Comment by pkmnfrk** [comment]
I don't know why I opened this issue. 1.13 wasn't ready at the time, and it still isn't, and I will be dead and turned to dust before it is ready.

Should that prediction be incorrect, I will revisit this.
