### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by luffykick** [pkmnfrk/equivalentintegrations#7]
This mod is awesome! But... I would greatly help if we get a config file, please? I was looking to set the power production rate.

**Comment by pkmnfrk** [comment]
Sorry, I missed this because I forgot to set my notification settings!

I'm assuming you're looking for something like a global modifier?

**Comment by pkmnfrk** [comment]
Wait, I forgot how my own mod worked! You set the production rate in the GUI. Therefore, this only makes sense if you want a multiplier to EMC consumed, yes?

**Comment by pkmnfrk** [comment]
I'm going to assume this is what you're looking for.
