### ISSUE TITLE
Incorrect EMC added for some items piped into Transmutation Chamber

### ISSUE THREAD

**Issue by Paulygon104** [pkmnfrk/equivalentintegrations#9]
Superflat creative test world with: Forge 14.23.4.2757, ProjectE 1.12-PE1.3.1B, Equivalent Integrations 0.1.5-PE1.3.1B, Extra Utilities 2 1.12.2-1.8.2, Redstone Flux 2.0.23.

To start with, I put a piece of cobblestone into the Transmutation Tablet, since the Transmutation Chamber wouldn't accept input with an empty table (perhaps a different bug).  Also, it wouldn't accept input from a hopper, so I had to add a tech mod with an item transport system.  The chamber inventory consisted of a maximum of 4 efficiency upgrades, along with the tome to be able to teach the tablet new items, as well as a talisman soulbound to my player.

I piped a dark matter into the chamber and the correct amount of 139,264 EMC was added.  Then I removed the dark matter, leaving only 1 EMC.  However, when I then piped in a red matter, the same amount of 139,264 EMC was incorrectly added, instead of 466,944 EMC.

I then used the projecte command to clear my player knowledge and subsequently relogged.  Teaching the red matter first then caused the opposite behavior.  This can be accomplished also by unlearning the respective items in the transmutation table/tablet and relogging.  Namely, red matter, when piped into the transmutation chamber first, added the correct value of 466,944 EMC and dark matter piped into the chamber afterward erroneously yielded the same 466,944 EMC.  It seems that whichever of the two items is taught first becomes the one that both items subsequently register as.  Relogging after removing the knowledge was necessary to get this behavior to change.

I was also able to get the same behavior between dark matter blocks and red matter blocks, presumably due to dynamic emc and related recipes.

Edit:  Just tested with compressed cobblestone from Extra Utilities 2 and the same thing happens.  If you teach regular compressed cobblestone (9 EMC) to the transmutation table first and then pipe a higher-tier block of compressed cobblestone into the Transmutation Chamber, you will only get 9 EMC instead of whatever it should've been worth.  Tried with octuple-compressed cobblestone and got 9 EMC instead of 43,046,721 EMC.

**Comment by pkmnfrk** [comment]
Interesting, hoppers shouldn't have any issues with this... Let me test and see what I turn up.

**Comment by pkmnfrk** [comment]
I've confirmed the empty table bug, and opened #10.

I cannot confirm the Hopper thing, it seems to work for me currently. However, I am still using an older version of Forge, so I will re-test with that.

(Still working on the actual meat of this bug)

**Comment by pkmnfrk** [comment]
Sorry, I was wrong, hoppers are broken as suggested. Opened #11.

**Comment by pkmnfrk** [comment]
Ok, confirmed the real bug here. It seems like it doesn't respect item metadata. In 1.13, this won't be an issue since there won't be metadata, but since this isn't 1.13....

Whoops!

**Comment by pkmnfrk** [comment]
If you have a chance, Please check out the 0.1.6 release (https://github.com/pkmnfrk/equivalentintegrations/releases/tag/v0.1.6) which should fix the issue.

**Comment by Paulygon104** [comment]
Hi, I've had a chance to check out the 0.1.6 release for PE1.3.1 and everything I reported seems to be fixed now, thank you!
